### ISSUE TITLE
chocolate-cakephp marked es incompatible with PHPStorm Version 2021.3.2

### ISSUE THREAD

**Issue by Alibert-07** [dmeybohm/chocolate-cakephp#59]
Any Thoughts? 

I would appreciate if someone could fix this! Can help Test it, but i'm not a "great" Java/Kotlin guy.

Thank You!

**Comment by dmeybohm** [comment]
I just tried it on 2021.3.2 with version 0.7.0 of the plugin, and it works for me. Which version of the Chocolate CakePHP do you have installed?

I'm wondering if you have an older version that is preventing you to update to version 0.7.0. Maybe you need to uninstall and re-install the plugin.

**Comment by dmeybohm** [comment]
@Alibert-07 Actually, I did a fresh install - but I do see a popup about the plugin being incompatible on upgrade.

As a workaround, you can try removing the plugin and re-installing. I'll see if I can release a new version that will resolve that.

**Comment by Alibert-07** [comment]
Did reinstall! Works fine now! Thank you for your support. Plugin is Great!!!!

**Comment by dmeybohm** [comment]
For posterity, this should be fixed in https://github.com/dmeybohm/chocolate-cakephp/pull/60
