### ISSUE TITLE
Add a way to navigate to the controller from a view file

### ISSUE THREAD

**Issue by dmeybohm** [dmeybohm/chocolate-cakephp#72]
Clicking on the Cake icon in the gutter from a controller goes to a corresponding view file. 

There should be a way to go back to the controller. Could add an overlay icon in the upper right, that way it doesn't depend on the scroll position.

**Comment by dmeybohm** [comment]
Additionally, it would be good if this would also work for elements to navigate to the files that use those elements.

**Comment by Alibert-07** [comment]
A "backlink" to the controller method from the view would be very much appreciated! 
From the Elements to view is also a good idea. Just discovered that clicking on the element name (this->element('**elementname**');) takes me to the element file. Very Nice.  $

**Comment by dmeybohm** [comment]
I opened a new issue for the navigation between views and elements: https://github.com/dmeybohm/chocolate-cakephp/issues/110

I implemented the navigation between views <-> controllers, and added a default keyboard shortcut: `ctrl-alt-UP` in https://github.com/dmeybohm/chocolate-cakephp/pull/109 that should be released soon

So closing this as resolved.
