### ISSUE TITLE
Make cake icon extract multiple possible view files

### ISSUE THREAD

**Issue by dmeybohm** [dmeybohm/chocolate-cakephp#73]
Sometimes a controller action has multiple different possible view files, and then clicking the Cake icon to navigate to the view only goes to the automatically configured one instead of the relevant one.

Scan the controller actions during the line marker building process and if an action contains any render calls, go to the views specified in the render calls. If more than one render call exists, make a drop down when clicking on the icon that displays all the relevant view files.

**Comment by makamo** [comment]
See also in folders like RSS, JSON, CSV, etc.

- Users
  - index.php
  - csv
    - index.php

**Comment by dmeybohm** [comment]
@makamo Thanks - I was not aware of that feature of CakePHP. I'll take a look at incorporating that.

**Comment by dmeybohm** [comment]
Addressed this in https://github.com/dmeybohm/chocolate-cakephp/pull/85 - will close this issue on next release.
